source: semantickitti
target: semantickitti 
cluster_cfg: ./cfg/clust_cfg/cluster_20.yaml
model_cfg: ./cfg/model_cfg/kpconv.yaml
data_cfg_path: ./cfg/data_cfg
subsample: 1 
save_pred_path: ./results_LabelProp
