source: nuscenes
target: paris
cluster_cfg: ./cfg/clust_cfg/cluster_20.yaml
model_cfg: ./cfg/model_cfg/kp_sk_infer.yaml
data_cfg_path: ./cfg/data_cfg
subsample: 1
save_pred_path: /home/3DLabelProp/saved_models
train_hd: True
test_hd: False
hd_param: './cfg/hd_param.yaml'
