architecture:
  model: KPCONV #KPCONV or SPVCNN
  type: KPFCNN #Config to fetch
  n_features: 1
trainer:
  epoch: 500000
  batch_size: 8
  lr: 0.02
  min_lr: 0.001
  epoch_lr: 350000
  optimizer: SGD
  momentum: 0.98
  weight_decay: 0.0001
  balanced: True
  criterion: Lovasz_weighted
  evaluate_timing: 50000
  evaluate_size: 500
  scheduler: CosineAnnealing
  step_size: 750
  resume: 0
logger:
  run_name: debug
  save_path: ./results_best
  model_name: best_kp_sk.pth
