apiVersion: apps/v1
kind: Deployment
metadata:
  name: label-prop
  labels:
    k8s-app: label-prop
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: label-prop
  template:
    metadata: 
      labels:
        k8s-app: label-prop
    spec:
      containers:
      - name: label-prop
        image: nvidia/cuda:11.1.1-cudnn8-devel-ubuntu18.04
        command: ["sleep", "infinity"]
        volumeMounts:
          - mountPath: /mnt/data
            name: data
          - mountPath: /root/main
            name: ivannia-volume
        resources:
          limits:
            nvidia.com/gpu: "1"
            memory: "16G"
            cpu: "1"
            ephemeral-storage: "512Gi"
          requests:
             memory: "16G"
             cpu: "1"
             ephemeral-storage: "512Gi"
      volumes:
        - name: ivannia-volume
          persistentVolumeClaim:
            claimName: ivannia-volume
        - name: data
          emptyDir: {}
      #affinity:
      #  nodeAffinity:
      #    requiredDuringSchedulingIgnoredDuringExecution:
      #      nodeSelectorTerms:
      #      - matchExpressions:
      #        - key: nvidia.com/gpu.product
      #          operator: In
      #          values:
      #          - NVIDIA-A10
                #- Tesla-V100-SXM2-32GB